### ISSUE TITLE
Pipes/Conduit/etc integration home

### ISSUE THREAD

**Issue by mitchellwrosen** [facebookexperimental/hs-zstd#1]
Just curious, is this git repo an appropriate place to develop/maintain the wrapper packages mentioned in the readme (e.g. `pipes-zstd`)?

**Comment by bos** [comment]
Yeah, we can put those packages in subdirectories of this repo.

**Comment by michaelt** [comment]
@mitchellwrosen  are you writing a pipes-zstd?

**Comment by mitchellwrosen** [comment]
@michaelt Not at the moment, but I was going to if no one else volunteered. You could probably write a better one than me =)

**Comment by michaelt** [comment]
Hah, I don't know. I made one for 'streaming bytestrings' since it was just a matter of relabeling things from the `...Zstd.Lazy` module.  https://github.com/michaelt/streaming-zstd The conduit and pipes treatments of zlib take various approaches to exceptions especially arising from decoding a bad stream; I'm not sure what to make of it.
